service: techstore-inventory-management
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: 
        - "arn:aws:dynamodb:us-east-1:907257771839:table/tech-store-products"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::tech-store-images-bucket/*"

functions:
  addProductInfos:
    handler: src/app.addProductHandler
    events:
      - http:
          path: /products
          method: POST

  updateProductInfos:
    handler: src/app.updateProductHandler
    events:
      - http:
          path: /products/{id}
          method: PUT
          request:
            parameters:
              paths:
                id: true

  verifyToken:
    handler: handler.verifyToken
    events:
      - http:
          path: /verifyToken
          method: POST


plugins:
  - serverless-iam-roles-per-function

resources: ${file(ymls/resources.yml)}
custom: ${file(ymls/custom.yml)}
